name: test-otoroshi-biscuit-studio

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup jdk11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: sbt/setup-sbt@v1.1.5
      - uses: coursier/cache-action@v6
      - name: Run sbt tests
        run: sbt test